admin/urls.py
from django.conf.urls.defaults import patterns, url
from views import *
from django.shortcuts import render

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', ShowSolveStatusView),
    url(r'^solver/(\w+)/', ShowSolverStatusView),
    url(r'^user/', SearchUserView),

    url(r'^challenge/', AdminChallengeManagerView),
    
    url(r'^add-tag/', AdminAddTagManagerView),
    url(r'^check-tag/', AdminTagCheckView),
    url(r'^modify-tag/', AdminModifyTagView),
    url(r'^delete-tag/', AdminDeleteTagView),
    
    url(r'^add-prob/', AdminAddProblemManagerView),
    url(r'^modify-prob/', AdminModifyProblemView),
    url(r'^delete-prob/', AdminDeleteProblemView),
    url(r'^problist/', AdminProblemListManagerView),

    url(r'^add-category/', AdminAddBoardCategoryView),
    url(r'^modify-category/(\w+)', AdminModifyBoardCategoryView),
    url(r'^delete-category/(\w+)', AdminDeleteBoardCategoryView),

    url(r'^manager-user/', AdminUserManagerView),
    url(r'^info-user/', AdminUserInfoView),
    url(r'^modify-user/', AdminModifyUserView),
    url(r'^delete-user/', AdminDeleteUserView),
    url(r'^admin-write/', AdminWritePostView),
    url(r'^userlist/', AdminUserListManagerView),

    url(r'^server-onoff/', ServerOnOffView),
    url(r'^change-rank/', RankModeChangeView),
)

board/urls.py
from django.conf.urls import patterns, url
from views import ShowPostListView, ShowPostOfCategoryListView, WritePostView, ShowPostContentView, ModifyPostView, DeletePostView

urlpatterns = patterns('',
    url(r'^$', ShowPostListView),
    url(r'^(\w+)/$', ShowPostOfCategoryListView),
    url(r'^write-post/', WritePostView),
    url(r'^show-post/(\w+)/', ShowPostContentView),

    url(r'^modify-post/(\w+)/', ModifyPostView),
    url(r'^delete-post/(\w+)/', DeletePostView),
)

hackspace/urls.py
from django.conf.urls import patterns, include, url
from django.shortcuts import render
import os

from member.views import * 
from challenge.views import *
from admin.views import *
from rank.views import ShowRankView

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', lambda request:render(request, 'index.html')),

    url(r'^register/', memberRegisterView),
    url(r'^login/', memberLoginView),
    url(r'^logout/', memberLogout),

    url(r'^challenge/$', ProbListView),
    url(r'^challenge/auth/',ChallengeAuthView),

    url(r'^rank/', ShowRankView),

    url(r'^admin/', include('admin.urls')),
    url(r'^board/', include('board.urls')),

    url(r'^static/(?P<path>.*)', 'django.views.static.serve', {'document_root': 'static'}),
    url(r'^uploads/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'uploads'})
)

board/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

class Category(models.Model):
    name = models.CharField(max_length=32, unique=True)

    def __str__(self):
        return self.name.encode('utf8')

class Board(models.Model):
    user = models.ForeignKey(User)
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=64)
    content = models.TextField()
    time = models.DateTimeField(auto_now_add=True)

board/forms.py
from django import forms
from models import Category
from django.db.models import Q

class PostForm(forms.Form):
    title = forms.CharField(label=u'title', widget=forms.TextInput())
    category = forms.ModelChoiceField(queryset=Category.objects.filter(~Q(id=1)))
    content = forms.CharField(label=u'content', widget=forms.Textarea())

class AdminPostForm(forms.Form):
    title = forms.CharField(label=u'title', widget=forms.TextInput())
    category = forms.ModelChoiceField(queryset=Category.objects.all())
    content = forms.CharField(label=u'content', widget=forms.Textarea())

admin/views/board_view.py
#-*-coding:utf-8-*-
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required

from board.models import Category, Board
from board.forms import AdminPostForm, PostForm
from admin.forms import CategoryForm

@login_required(login_url='/login/')
def AdminWritePostView(request):
    if request.user.is_superuser:
        if request.method == 'POST':
            form = AdminPostForm(request.POST)
            if form.is_valid():
                post = Board(user=request.user,
                             category=form.cleaned_data['category'],
                             title=form.cleaned_data['title'],
                             content=form.cleaned_data['content'])
                post.save()
                return HttpResponseRedirect('/admin/add-category/')
        else:
            form = AdminPostForm(initial=request.GET)
        return render(request, 'board/write_post.html', dict(form=form))
    else:
        form = PostForm(initial=request.GET)
        return render(request, 'board/write_post.html', dict(form=form))

@login_required(login_url='/login/')
def AdminAddBoardCategoryView(request):
    if request.user.is_superuser:
        categories = Category.objects.all()
        posts = Board.objects.order_by('-time')[:10]
        if request.method == 'POST':
            form = CategoryForm(request.POST)
            if form.is_valid():
                Category.objects.create(name=form.cleaned_data['category_name'])
        else:
            form = CategoryForm(initial=request.GET)
        return render(request, 'admin/board_manage/category_add.html', dict(form=form,
                                                                     categories=categories,
                                                                     posts=posts))
    else:
        return HttpResponseRedirect('/')

@login_required(login_url='/login/')
def AdminModifyBoardCategoryView(request, category_id):
    if request.user.is_superuser:
        categories = Category.objects.all()
        posts = Board.objects.order_by('-time')[:10]
        try:
            category = Category.objects.get(id=category_id)
            default = {
                'category_name' : category.name
            }
            if request.method == 'POST':
                form = CategoryForm(request.POST)
                if form.is_valid():
                    category.name = form.cleaned_data['category_name']
                    category.save()
                    return HttpResponseRedirect('/admin/add-category/')
            else:
                form = CategoryForm(initial=default)
                return render(request, 'admin/board_manage/category_modify.html', dict(form=form,
                                                                                categories=categories,
                                                                                category_id=category_id,
                                                                                posts=posts))
        except:
            return HttpResponseRedirect('/admin/add-category/')
    else:
        return HttpResponseRedirect('/')

@login_required(login_url='/login/')
def AdminDeleteBoardCategoryView(request, category_id):
    if request.user.is_superuser:
        try:
            category = Category.objects.get(id=category_id)
            posts = Board.objects.filter(category_id=category_id)
            etc_category = Category.objects.get(id=2)
            for post in posts:
                post.category_id = etc_category
                post.save()
            category.delete()
        except Category.DoesNotExist:
            pass
        return HttpResponseRedirect('/admin/add-category/')
    else:
        return HttpResponseRedirect('/')

board/views.py
#-*-coding:utf-8-*-
from models import Board, Category
from forms import PostForm, AdminPostForm

from django.db.models import Q
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse

@login_required(login_url='/login/')
def WritePostView(request):
    if request.method == 'POST':
        if request.user.is_superuser:
            form = AdminPostForm(request.POST)
        else:
            form = PostForm(request.POST)
        if form.is_valid():
            post = Board(user=request.user,
                         category=form.cleaned_data['category'],
                         title=form.cleaned_data['title'],
                         content=form.cleaned_data['content'])
            post.save()
            return HttpResponseRedirect('/board/')
    else:
        if request.user.is_superuser:
            form = AdminPostForm(initial=request.GET)
        else:
            form = PostForm(initial=request.GET)
    return render(request, 'board/write_post.html', dict(form=form))

@login_required(login_url='/login/')
def ShowPostListView(request):
    posts = Board.objects.order_by('category', '-time')
    categories = Category.objects.all()
    return render(request, 'board/board.html', dict(posts=posts,
                                                               categories=categories))

@login_required(login_url='/login/')
def ShowPostOfCategoryListView(request, category_id):
    try:
        categories = Category.objects.all()
        categoryList = []
        for category in categories:
            categoryList.append(category.id)
        selectedCategory = categoryList.index(int(category_id))+1
        posts = Board.objects.filter(category=category_id).order_by('-time')
    except:
        posts = Board.objects.all().order_by('category', '-time')
        categories = Category.objects.all()
        selectedCategory = 0
    return render(request, 'board/board.html', dict(posts=posts,
                                                               categories=categories,
                                                               selectedCategory=selectedCategory))

@login_required(login_url='/login/')
def ShowPostContentView(request, post_id):
    try:
        post = Board.objects.get(id=post_id)
        if post.user.id == request.user.id:
            is_author = True
        else:
            is_author = False
        return render(request, 'board/render_post_content.html', dict(post=post, is_author=is_author))
    except Board.DoesNotExist:
        return HttpResponseRedirect('/board/')

@login_required(login_url='/login/')
def ModifyPostView(request, post_id):
    try:
        post = Board.objects.get(id=post_id, user=request.user)
        default = {
            'category' : post.category,
            'title' : post.title,
            'content' : post.content
        }
        if request.method == 'POST':
            if request.user.is_superuser:
                form = AdminPostForm(request.POST)
            else:
                form = PostForm(request.POST)
            if form.is_valid():
                post.category = form.cleaned_data['category']
                post.title = form.cleaned_data['title']
                post.content = form.cleaned_data['content']
                post.save()
                return HttpResponseRedirect('/board/show-post/%s' % post_id)
        else:
            if request.user.is_superuser:
                form = AdminPostForm(initial=default)
            else:
                form = PostForm(initial=default)
        return render(request, 'board/write_post.html', dict(form=form))
    except Board.DoesNotExist:
        return HttpResponseRedirect('/board/show-post/%s' % post_id)
    return HttpResponseRedirect('/board/')

@login_required(login_url='/login/')
def DeletePostView(request, post_id):
    try:
        post = Board.objects.get(id=post_id, user=request.user)
        post.delete()
        return HttpResponseRedirect('/board/')
    except Board.DoesNotExist:
        if request.user.is_superuser:
            post = Board.objects.get(id=post_id)
            post.delete()
            return HttpResponseRedirect('/board/')
        else:
            return HttpResponseRedirect('/board/show-post/%s' % post_id)

templates/board/board.html
{% extends "base.html" %}
{% block title %} Board {% endblock %}
{% block board_active %}active{% endblock %}
{% block content %}
<h1 class="pager">Board</h1>
<div class="row-fluid">
    {% include "board/render_category_list.html" %}
</div>
<hr>
    {% include "board/render_post_list.html" %}
{% endblock %}

templates/board/render_category_list.html
<div class="span5">
    {% if not selectedCategory or selectedCategory == 0 %}
        <a href="/board/"><button type="button" class="btn btn-info">All</button></a>
    {% else %}
        <a href="/board/"><button type="button" class="btn">All</button></a>
    {% endif %}
    {% for category in categories %}
        {% if selectedCategory == forloop.counter %}
            <a href="/board/{{ category.id }}"><button type="button" class="btn btn-info">{{ category.name }}</button></a>
        {% else %}
            <a href="/board/{{ category.id }}"><button type="button" class="btn">{{ category.name }}</button></a>
        {% endif %}
    {% endfor %}
</div>
<div class="span1 offset6">
    <a href="/board/write-post/"><button type="button" class="btn">Write</button></a>
</div>

templates/board/render_post_content.html
{% extends "base.html" %}
{% block title %} Board {% endblock %}
{% block board_active %}active{% endblock %}
{% block style_external %}
<style type="text/css">
    .text {
        text-align:right;
        text-decoration:underline;
    }
    .btns {
        width: 400px;
        margin-left: 82%;
    }
</style>
{% endblock %}
{% block content %}
<h1>{{ post.title }}</h1>
<p>[{{ post.category.name }}] {{ post.time }}</p>
<hr>
<div style="width:80%">
    <blockquote>{{ post.content|linebreaksbr }}</blockquote>
</div>
<p class="text">Posted by {{ post.user.username }}</p>
<hr>
<div class="btns">
    <a href="/board/"><button type="button" class="btn">Back</button></a>
    {% if is_author%}
    <a href="/board/modify-post/{{ post.id }}"><button type="button" class="btn">Modify</button></a>
    {% endif %}
    {% if is_author or user.is_superuser %}
    <a href="/board/delete-post/{{ post.id }}"><button type="button" class="btn">Delete</button></a>
    {% endif %}
</div>
{% endblock %}

templates/board/render_post_list.html
<table class="table table-hover">
    <tr class="info">
        <td>No</td>
        <td>User</td>
        <td>Title</td>
        <td>Time</td>
    </tr>
    {% for post in posts %}
        {% if post.category.id == 1 %}
            <tr class="error">
        {% else %}
            <tr>
        {% endif %}
        <td>{{ forloop.counter }}</td>
        <td>{{ post.user.username }}</td>
        <td><a href="/board/show-post/{{ post.id }}">{{ post.title }}</a></td>
        <td>{{ post.time }}</td>
    </tr>
    {% endfor %}
</table>

templates/board/write_post.html
{% extends "base.html" %}
{% block title %} Post {% endblock %}
{% block board_active %}active{% endblock %}
{% block style_external %}
<style type="text/css">
    #id_title {
        width: 60%;
    }
    #id_category {
        width: 20%;
    }
    #id_content {
        width: 80%;
    }
</style>
{% endblock %}
{% block content %}
<form method="post" class="form-inline form-horizontal">
    {{ form.category }}
    {{ form.title }}
    <hr>
    <div class="control-group">
        {{ form.content }}
    </div>
    <button type="submit" class="btn">Write</button>
    {% csrf_token %}
</form>
{% endblock %}